### ISSUE TITLE
Copyright ©️

### ISSUE THREAD

**Issue by DanielcoderX** [electron-v2ray/Free-V2ray-AutoRun-Advanced#9]
Hi, You added **Gheychi** sub's and you are **breaching** _open source_ term's 
**Gheychi** provides this sub's for **free** to users but **didn't allowed** them to share as a **public** and each sub is individually for each person

**Comment by electron-v2ray** [comment]
This sub has no copyright, I have received written permission
https://t.me/alicivil
![Screenshot (43)](https://user-images.githubusercontent.com/129282445/236615007-637df33a-314c-4be2-874d-5624bf35fa35.png)

**Comment by DanielcoderX** [comment]
> This sub has no copyright, I have received written permission
> https://t.me/alicivil
> ![Screenshot (43)](https://user-images.githubusercontent.com/129282445/236615007-637df33a-314c-4be2-874d-5624bf35fa35.png)
> 

Exactly from who?? The owner is **Mr. Amin Anvari** and they've just published sansorchi android app(currently out of order) and Gheychi telegram bot which gives an individual sub

[Sansorchi telegram channel](https://t.me/ml9Qk0OUpkNzFl)

![Screenshot_20230506-144858__01.jpg](https://user-images.githubusercontent.com/68733224/236621037-213d02a0-b86f-4870-8611-d13c885b5000.jpg)

**Comment by electron-v2ray** [comment]
You have misunderstood the issue with the "sub". This is a sub worker that is used to edit the configuration, not the Ghichi bot channel.

**Comment by DanielcoderX** [comment]
Alright, have a Good Day
